spring.application.name=edutrack-backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

server.address=0.0.0.0
server.port=${PORT:8080}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:validate}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:https://edutrackpe.vercel.app,https://*.vercel.app,http://localhost:5173,http://127.0.0.1:5173}
app.bootstrap.admin-email=${ADMIN_BOOTSTRAP_EMAIL:}
app.bootstrap.admin-password=${ADMIN_BOOTSTRAP_PASSWORD:}
app.bootstrap.admin-first-name=${ADMIN_BOOTSTRAP_FIRST_NAME:Administrador}
app.bootstrap.admin-last-name=${ADMIN_BOOTSTRAP_LAST_NAME:EduTrack}
